### ISSUE TITLE
Messages not readable when dark theme enabled

### ISSUE THREAD

**Issue by rworkm** [eblah/nextcloud-messagevault#2]
Message background does not change when the Nextcloud dark theme (found under Settings -> Accessibility) is enabled but the text color does change.  This make messages unreadable as the text changes to white and the background of the message is very light colored.

**Comment by onfire4g05** [comment]
I believe this is fixed, but I haven't been able to push an app update yet. I still have some other cleanup I need to do with the new thread-search feature.
